# Generated by Django 4.0.3 on 2023-03-03 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closet_name', models.CharField(max_length=150)),
                ('bin_number', models.PositiveIntegerField(null=True)),
                ('bin_size', models.PositiveIntegerField(null=True)),
                ('import_href', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_brand', models.CharField(max_length=200)),
                ('shoe_name', models.CharField(max_length=200)),
                ('shoe_color', models.CharField(max_length=200)),
                ('shoe_picture_url', models.URLField(null=True)),
                ('bin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoe', to='shoes_rest.binvo')),
            ],
        ),
    ]
